# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'healthyMinD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for healthyMinD

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Database'

  target 'healthyMinDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'healthyMinDUITests' do
    # Pods for testing
  end

end
